// Guard tests for the A2A Agent Card (#54) — run with `npm test` (Node's
// built-in runner, no network access required).
//
// Issue #54 asks for an A2A Agent Card at /.well-known/agent-card.json
// carrying name, version, supportedInterfaces, capabilities and skills, per
// https://isitagentready.com/.well-known/agent-skills/a2a-agent-card/SKILL.md
// (A2A spec §4.4.1). The card is generated by scripts/well-known.mjs from the
// canonical shape in scripts/agent-card.mjs; these tests pin the schema, the
// honesty guards (no A2A endpoint the site does not serve), and the
// card ↔ WebMCP tool sync.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

import {
  AGENT_CARD,
  AGENT_CARD_PATH,
  AGENT_CARD_URL,
  A2A_CORE_BINDINGS,
  WEBMCP_PROTOCOL_BINDING,
  DOC_SKILLS,
  buildAgentCard,
} from '../scripts/agent-card.mjs';
import {
  evaluateAgentCardResponse,
  validateAgentCard,
} from '../scripts/verify-agent-card.mjs';
import { buildTools } from '../src/webmcp.js';

const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
const wellKnownSrc = readFileSync('scripts/well-known.mjs', 'utf8');

// ---------------------------------------------------------------------------
// Schema — the required set the guide and A2A spec §4.4.1 name
// ---------------------------------------------------------------------------

test('generated card validates clean against the AgentCard schema', () => {
  const { ok, problems } = validateAgentCard(AGENT_CARD);
  assert.deepEqual(problems, []);
  assert.ok(ok);
});

test('card carries the guide-required fields', () => {
  for (const field of ['name', 'version', 'description']) {
    assert.ok(
      typeof AGENT_CARD[field] === 'string' && AGENT_CARD[field].trim(),
      `${field} must be a non-empty string`,
    );
  }
  assert.equal(AGENT_CARD.name, 'MILO');
  assert.equal(AGENT_CARD.version, pkg.version);
});

test('supportedInterfaces declares a URL and a transport protocol', () => {
  assert.ok(Array.isArray(AGENT_CARD.supportedInterfaces));
  assert.ok(AGENT_CARD.supportedInterfaces.length >= 1);
  for (const iface of AGENT_CARD.supportedInterfaces) {
    assert.match(iface.url, /^https:\/\/askmilo\.pro\//);
    assert.equal(typeof iface.protocolBinding, 'string');
    assert.ok(iface.protocolBinding.length > 0);
    assert.equal(typeof iface.protocolVersion, 'string');
    assert.ok(iface.protocolVersion.length > 0);
  }
});

test('card claims no A2A endpoint the static site does not serve', () => {
  // §8.3.1: every declared interface MUST be accurate. askmilo.pro is a
  // static site — the only real agent surface is WebMCP on the homepage, so
  // no core binding (JSONRPC/GRPC/HTTP+JSON) may appear.
  for (const iface of AGENT_CARD.supportedInterfaces) {
    assert.ok(
      !A2A_CORE_BINDINGS.includes(iface.protocolBinding),
      `${iface.protocolBinding} claims an A2A endpoint that does not exist`,
    );
  }
  assert.equal(AGENT_CARD.supportedInterfaces.length, 1);
  assert.equal(
    AGENT_CARD.supportedInterfaces[0].protocolBinding,
    WEBMCP_PROTOCOL_BINDING,
  );
  assert.equal(AGENT_CARD.supportedInterfaces[0].url, 'https://askmilo.pro/');
});

test('capabilities and default modes are declared honestly', () => {
  assert.equal(typeof AGENT_CARD.capabilities, 'object');
  // No streaming or push machinery exists behind the site.
  assert.equal(AGENT_CARD.capabilities.streaming, false);
  assert.equal(AGENT_CARD.capabilities.pushNotifications, false);
  for (const field of ['defaultInputModes', 'defaultOutputModes']) {
    assert.ok(Array.isArray(AGENT_CARD[field]) && AGENT_CARD[field].length > 0);
    for (const mode of AGENT_CARD[field]) {
      assert.equal(typeof mode, 'string');
    }
  }
});

test('every skill carries id, name, description and tags', () => {
  assert.ok(AGENT_CARD.skills.length >= 1);
  const ids = new Set();
  for (const skill of AGENT_CARD.skills) {
    for (const field of ['id', 'name', 'description']) {
      assert.ok(
        typeof skill[field] === 'string' && skill[field].trim(),
        `skill ${skill.id ?? '?'} missing ${field}`,
      );
    }
    assert.ok(Array.isArray(skill.tags) && skill.tags.length > 0);
    assert.ok(!ids.has(skill.id), `duplicate skill id ${skill.id}`);
    ids.add(skill.id);
  }
});

// ---------------------------------------------------------------------------
// Card ↔ WebMCP tool sync — the card may only offer tools the site runs
// ---------------------------------------------------------------------------

test('every WebMCP tool is advertised as a card skill, verbatim', () => {
  const skillsById = new Map(AGENT_CARD.skills.map((s) => [s.id, s]));
  for (const tool of buildTools()) {
    const skill = skillsById.get(tool.name);
    assert.ok(skill, `tool ${tool.name} is missing from the card`);
    assert.equal(skill.name, tool.title);
    assert.equal(skill.description, tool.description);
    assert.ok(skill.tags.length > 0, `tool ${tool.name} has no tags`);
  }
});

test('card skills map only to real surfaces: WebMCP tools or published skill docs', () => {
  const toolNames = new Set(buildTools().map((t) => t.name));
  for (const skill of AGENT_CARD.skills) {
    if (toolNames.has(skill.id)) continue;
    assert.ok(
      existsSync(`public/.well-known/agent-skills/${skill.id}/SKILL.md`),
      `skill ${skill.id} is neither a WebMCP tool nor a published skill doc`,
    );
  }
});

test('documented skill description tracks the SKILL.md frontmatter', () => {
  const src = readFileSync(
    'public/.well-known/agent-skills/milo-hands-free-ai-via-siri/SKILL.md',
    'utf8',
  );
  const description = src
    .match(/^---\r?\n([\s\S]*?)\r?\n---/)[1]
    .match(/^description:\s*(.+)$/m)[1]
    .trim();
  assert.equal(DOC_SKILLS[0].description, description);
});

// ---------------------------------------------------------------------------
// Build wiring — the card must actually land in dist/
// ---------------------------------------------------------------------------

test('well-known.mjs emits the card at the probed path', () => {
  assert.match(wellKnownSrc, /agent-card\.mjs/);
  assert.ok(
    wellKnownSrc.includes(`dist${AGENT_CARD_PATH}`),
    `well-known.mjs must write dist${AGENT_CARD_PATH}`,
  );
});

test('card URL and path are the ones the scanner probes', () => {
  assert.equal(AGENT_CARD_PATH, '/.well-known/agent-card.json');
  assert.equal(AGENT_CARD_URL, 'https://askmilo.pro/.well-known/agent-card.json');
});

test('serialized card is JSON and free of secret-scan hazard strings', () => {
  const serialized = JSON.stringify(buildAgentCard());
  assert.doesNotThrow(() => JSON.parse(serialized));
  // The slugged App Store URL shape matches the sk-* real-key scan; the
  // canonical id-only URL is the only acceptable form.
  assert.doesNotMatch(serialized, /sk-milo/);
});

// ---------------------------------------------------------------------------
// Live-response evaluation — the verdict the verifier reports
// ---------------------------------------------------------------------------

test('evaluate passes a 200 response carrying the canonical card', () => {
  const res = evaluateAgentCardResponse({
    ok: true,
    status: 200,
    contentType: 'application/json',
    body: JSON.stringify(AGENT_CARD),
  });
  assert.equal(res.status, 'pass');
  assert.equal(res.evidence.httpStatus, 200);
});

test('evaluate fails a 404 the way the scanner saw it', () => {
  const res = evaluateAgentCardResponse({
    ok: false,
    status: 404,
    contentType: 'text/html; charset=utf-8',
    body: '<html>not found</html>',
  });
  assert.equal(res.status, 'fail');
  assert.match(res.message, /404/);
});

test('evaluate fails on non-JSON and on missing required fields', () => {
  assert.equal(
    evaluateAgentCardResponse({
      ok: true,
      status: 200,
      contentType: 'application/json',
      body: 'not json{',
    }).status,
    'fail',
  );
  const res = evaluateAgentCardResponse({
    ok: true,
    status: 200,
    contentType: 'application/json',
    body: JSON.stringify({ name: 'MILO' }),
  });
  assert.equal(res.status, 'fail');
  assert.match(res.message, /supportedInterfaces/);
});

test('validateAgentCard flags broken interfaces and untagged skills', () => {
  const broken = buildAgentCard();
  broken.supportedInterfaces = [{ url: '/relative', protocolBinding: '' }];
  const { ok, problems } = validateAgentCard(broken);
  assert.equal(ok, false);
  assert.ok(problems.some((p) => p.includes('supportedInterfaces[0].url')));
  assert.ok(problems.some((p) => p.includes('protocolBinding')));

  const untagged = buildAgentCard();
  untagged.skills = [{ id: 'x', name: 'x', description: 'x', tags: [] }];
  assert.equal(validateAgentCard(untagged).ok, false);
});
