// Guard tests for the RFC 9727 API catalog (#56) — run with `npm test`
// (Node's built-in runner, no network access required).
//
// Issue #56 asks for /.well-known/api-catalog answering
// application/linkset+json with a "linkset" array listing the site's APIs and
// their specs, per
// https://isitagentready.com/.well-known/agent-skills/api-catalog/SKILL.md
// (RFC 9727 §4, Appendix A.1). The catalog is generated by
// scripts/well-known.mjs from the canonical shape in scripts/api-catalog.mjs;
// these tests pin the linkset schema, the honesty guards (no endpoint or
// relation the static site does not serve), the Content-Type transform rule,
// and the build wiring.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

import {
  API_CATALOG,
  API_CATALOG_PATH,
  API_CATALOG_URL,
  CONTENT_TYPE_VALUE,
  CATALOG_RELS,
  DOMAIN,
  LINKSET_MEDIA_TYPE,
  LINKSET_PROFILE,
  REQUIRED_ENTRY_RELS,
  RULE_DESCRIPTION_PREFIX,
  RULE_EXPRESSION,
  SELF_LINK_VALUE,
  buildApiCatalog,
  isManagedRule,
  renderRule,
} from '../scripts/api-catalog.mjs';
import { isManagedRule as isLinkHeadersRule } from '../scripts/link-headers.mjs';
import {
  SCANNER_ACCEPT,
  evaluateApiCatalogResponse,
  isLinksetContentType,
  validateApiCatalog,
} from '../scripts/verify-api-catalog.mjs';

const wellKnownSrc = readFileSync('scripts/well-known.mjs', 'utf8');

// ---------------------------------------------------------------------------
// Linkset schema — the shape RFC 9727 §4.2 / Appendix A.1 and the guide name
// ---------------------------------------------------------------------------

test('generated catalog validates clean against the linkset schema', () => {
  const { ok, problems } = validateApiCatalog(API_CATALOG);
  assert.deepEqual(problems, []);
  assert.ok(ok);
});

test('catalog carries a linkset array with an anchored entry', () => {
  assert.ok(Array.isArray(API_CATALOG.linkset));
  assert.ok(API_CATALOG.linkset.length >= 1);
  for (const entry of API_CATALOG.linkset) {
    assert.match(entry.anchor, /^https:\/\/askmilo\.pro\//);
  }
  assert.equal(API_CATALOG.linkset[0].anchor, 'https://askmilo.pro/');
});

test('every entry carries the guide-required relations', () => {
  for (const entry of API_CATALOG.linkset) {
    for (const rel of REQUIRED_ENTRY_RELS) {
      assert.ok(
        Array.isArray(entry[rel]) && entry[rel].length > 0,
        `entry ${entry.anchor} missing required relation "${rel}"`,
      );
    }
    for (const rel of Object.keys(entry)) {
      if (rel === 'anchor') continue;
      assert.ok(
        CATALOG_RELS.includes(rel) || rel === 'status' || rel === 'item',
        `unexpected relation "${rel}" on entry ${entry.anchor}`,
      );
    }
  }
});

test('catalog claims no status endpoint the static site does not serve', () => {
  // RFC 9727's `status` relation points at a health/status endpoint — the
  // site has none, so the relation must be absent rather than invented.
  for (const entry of API_CATALOG.linkset) {
    assert.equal(entry.status, undefined);
  }
});

// ---------------------------------------------------------------------------
// Honesty — every linked resource must be one the site actually serves
// ---------------------------------------------------------------------------

test('every catalog link is an absolute https URL on the askmilo.pro origin', () => {
  for (const entry of API_CATALOG.linkset) {
    for (const rel of CATALOG_RELS) {
      for (const link of entry[rel] ?? []) {
        assert.ok(
          link.href.startsWith(`https://${DOMAIN}/`),
          `${rel} link ${link.href} leaves the origin`,
        );
        assert.equal(typeof link.type, 'string');
        assert.ok(link.type.includes('/'), `${link.type} is not a media type`);
      }
    }
  }
});

test('every catalog link target is a resource the site actually serves', () => {
  for (const entry of API_CATALOG.linkset) {
    for (const rel of CATALOG_RELS) {
      for (const link of entry[rel] ?? []) {
        const pathname = new URL(link.href).pathname;
        const served =
          existsSync(`public${pathname}`) ||
          // Generated artifacts (agent-card.json, agent-skills/index.json,
          // api-catalog) are written into dist/ by scripts/well-known.mjs.
          wellKnownSrc.includes(`dist${pathname}`);
        assert.ok(
          served,
          `${link.href} is neither in public/ nor emitted by well-known.mjs`,
        );
      }
    }
  }
});

// ---------------------------------------------------------------------------
// Media type and probed path — what the scanner requires on the wire
// ---------------------------------------------------------------------------

test('catalog path and media type are the ones the scanner probes', () => {
  assert.equal(API_CATALOG_PATH, '/.well-known/api-catalog');
  assert.equal(API_CATALOG_URL, 'https://askmilo.pro/.well-known/api-catalog');
  assert.equal(LINKSET_MEDIA_TYPE, 'application/linkset+json');
  // RFC 9727 §4.2: the Linkset SHOULD carry the profile parameter.
  assert.ok(CONTENT_TYPE_VALUE.startsWith(`${LINKSET_MEDIA_TYPE};`));
  assert.ok(CONTENT_TYPE_VALUE.includes(`profile="${LINKSET_PROFILE}"`));
});

test('scanner Accept header is replayed verbatim by the verifier', () => {
  assert.equal(
    SCANNER_ACCEPT,
    'application/linkset+json, application/json',
  );
});

// ---------------------------------------------------------------------------
// Build wiring — the catalog must actually land in dist/
// ---------------------------------------------------------------------------

test('well-known.mjs emits the catalog at the probed path', () => {
  assert.match(wellKnownSrc, /api-catalog\.mjs/);
  assert.ok(
    wellKnownSrc.includes(`dist${API_CATALOG_PATH}`),
    `well-known.mjs must write dist${API_CATALOG_PATH}`,
  );
});

test('serialized catalog is JSON and free of secret-scan hazard strings', () => {
  const serialized = JSON.stringify(buildApiCatalog());
  assert.doesNotThrow(() => JSON.parse(serialized));
  // The slugged App Store URL shape matches the sk-* real-key scan; the
  // canonical id-only URL is the only acceptable form.
  assert.doesNotMatch(serialized, /sk-milo/);
});

// ---------------------------------------------------------------------------
// Transform rule — closes the GitHub Pages octet-stream gap at the edge
// ---------------------------------------------------------------------------

test('renderRule emits a scoped response-header transform rule', () => {
  const rule = renderRule();
  assert.equal(rule.action, 'rewrite');
  assert.equal(rule.enabled, true);
  assert.equal(rule.expression, RULE_EXPRESSION);
  assert.ok(rule.expression.includes(`http.request.uri.path eq "${API_CATALOG_PATH}"`));
  assert.ok(rule.description.startsWith(RULE_DESCRIPTION_PREFIX));
  const headers = rule.action_parameters.headers;
  assert.equal(headers['Content-Type'].operation, 'set');
  assert.equal(headers['Content-Type'].value, CONTENT_TYPE_VALUE);
  // RFC 9727 §2: the well-known URI answers a Link header with the
  // api-catalog relation on itself.
  assert.equal(headers.Link.operation, 'set');
  assert.equal(headers.Link.value, SELF_LINK_VALUE);
});

test('isManagedRule matches only the api-catalog description prefix', () => {
  assert.equal(isManagedRule(renderRule()), true);
  assert.equal(isManagedRule({ description: 'someone else’s rule' }), false);
  // The link-headers rule shares the same phase but is foreign to this tool.
  assert.equal(isManagedRule({ description: 'link-headers: …' }), false);
  assert.equal(isManagedRule({}), false);
  assert.equal(isManagedRule(null), false);
});

test('link-headers publish tooling does not claim the api-catalog rule', () => {
  assert.equal(isLinkHeadersRule(renderRule()), false);
});

// ---------------------------------------------------------------------------
// Live-response evaluation — the verdict the verifier reports
// ---------------------------------------------------------------------------

test('evaluate passes a 200 linkset+json response carrying the canonical catalog', () => {
  const res = evaluateApiCatalogResponse({
    ok: true,
    status: 200,
    contentType: CONTENT_TYPE_VALUE,
    body: JSON.stringify(API_CATALOG),
  });
  assert.equal(res.status, 'pass');
  assert.equal(res.evidence.httpStatus, 200);
});

test('evaluate fails a 404 the way the scanner saw it', () => {
  const res = evaluateApiCatalogResponse({
    ok: false,
    status: 404,
    contentType: 'text/html; charset=utf-8',
    body: '<html>not found</html>',
  });
  assert.equal(res.status, 'fail');
  assert.match(res.message, /404/);
});

test('evaluate fails the bare octet-stream response GitHub Pages emits', () => {
  // Without the transform rule the body is right but the media type is not —
  // the guide names application/linkset+json as a requirement, so this is a
  // fail, not a pass-with-warning.
  const res = evaluateApiCatalogResponse({
    ok: true,
    status: 200,
    contentType: 'application/octet-stream',
    body: JSON.stringify(API_CATALOG),
  });
  assert.equal(res.status, 'fail');
  assert.match(res.message, /Content-Type/);
});

test('evaluate fails on non-JSON and on missing required fields', () => {
  assert.equal(
    evaluateApiCatalogResponse({
      ok: true,
      status: 200,
      contentType: CONTENT_TYPE_VALUE,
      body: 'not json{',
    }).status,
    'fail',
  );
  const res = evaluateApiCatalogResponse({
    ok: true,
    status: 200,
    contentType: CONTENT_TYPE_VALUE,
    body: JSON.stringify({ linkset: [{ 'service-desc': [] }] }),
  });
  assert.equal(res.status, 'fail');
  assert.match(res.message, /anchor/);
});

test('isLinksetContentType ignores parameters but not the media type', () => {
  assert.equal(isLinksetContentType(CONTENT_TYPE_VALUE), true);
  assert.equal(
    isLinksetContentType('application/linkset+json; charset=utf-8'),
    true,
  );
  assert.equal(isLinksetContentType('application/octet-stream'), false);
  assert.equal(isLinksetContentType('application/json'), false);
  assert.equal(isLinksetContentType(null), false);
});

test('validateApiCatalog flags broken entries and relation link objects', () => {
  const broken = buildApiCatalog();
  broken.linkset = [{ anchor: '/relative' }];
  const { ok, problems } = validateApiCatalog(broken);
  assert.equal(ok, false);
  assert.ok(problems.some((p) => p.includes('linkset[0].anchor')));
  assert.ok(problems.some((p) => p.includes('service-desc')));

  const badLink = buildApiCatalog();
  badLink.linkset[0]['service-doc'] = [{ href: 'not-a-url' }];
  const result = validateApiCatalog(badLink);
  assert.equal(result.ok, false);
  assert.ok(
    result.problems.some((p) => p.includes('service-doc[0].href')),
  );
});
