// Guard tests for the MCP Server Card (#59) — run with `npm test` (Node's
// built-in runner, no network access required).
//
// Issue #59 asks for an MCP Server Card at /.well-known/mcp/server-card.json
// carrying serverInfo, a transport endpoint and capabilities, per
// https://isitagentready.com/.well-known/agent-skills/mcp-server-card/SKILL.md
// (SEP-1649 draft schema). The card is generated by scripts/well-known.mjs
// from the canonical shape in scripts/mcp-server-card.mjs; these tests pin
// the schema, the honesty guards (no MCP wire endpoint the site does not
// serve), and the card ↔ WebMCP tool sync.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { WEBMCP_PROTOCOL_BINDING } from '../scripts/agent-card.mjs';
import {
  MCP_SERVER_CARD,
  MCP_SERVER_CARD_PATH,
  MCP_SERVER_CARD_URL,
  MCP_WIRE_TRANSPORTS,
  SERVER_CARD_SCHEMA,
  WEBMCP_TRANSPORT_TYPE,
  buildServerCard,
} from '../scripts/mcp-server-card.mjs';
import {
  evaluateServerCardResponse,
  validateServerCard,
} from '../scripts/verify-mcp-server-card.mjs';
import { buildTools } from '../src/webmcp.js';

const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
const wellKnownSrc = readFileSync('scripts/well-known.mjs', 'utf8');

// ---------------------------------------------------------------------------
// Schema — the required set the guide and SEP-1649 draft name
// ---------------------------------------------------------------------------

test('generated card validates clean against the Server Card schema', () => {
  const { ok, problems } = validateServerCard(MCP_SERVER_CARD);
  assert.deepEqual(problems, []);
  assert.ok(ok);
});

test('card carries the guide-required fields', () => {
  assert.equal(MCP_SERVER_CARD.$schema, SERVER_CARD_SCHEMA);
  assert.equal(typeof MCP_SERVER_CARD.version, 'string');
  assert.equal(typeof MCP_SERVER_CARD.protocolVersion, 'string');
  assert.equal(MCP_SERVER_CARD.serverInfo.name, 'askmilo-pro-webmcp');
  assert.equal(MCP_SERVER_CARD.serverInfo.version, pkg.version);
  assert.equal(typeof MCP_SERVER_CARD.serverInfo.title, 'string');
});

test('transport declares a type and an endpoint URL', () => {
  assert.equal(typeof MCP_SERVER_CARD.transport.type, 'string');
  assert.ok(MCP_SERVER_CARD.transport.type.length > 0);
  assert.match(MCP_SERVER_CARD.transport.endpoint, /^https:\/\/askmilo\.pro\//);
});

// ---------------------------------------------------------------------------
// Honesty guards — the card may not claim an MCP endpoint the static site
// does not serve (same convention as the A2A Agent Card, tests/agent-card)
// ---------------------------------------------------------------------------

test('card claims no MCP wire endpoint the static site does not serve', () => {
  // The draft types transport.type as an open string; streamable-http/sse/
  // stdio are the wire transports. askmilo.pro is a static site — the only
  // real agent surface is WebMCP on the homepage, so none may appear.
  assert.ok(
    !MCP_WIRE_TRANSPORTS.includes(MCP_SERVER_CARD.transport.type),
    `${MCP_SERVER_CARD.transport.type} claims an MCP endpoint that does not exist`,
  );
  // The declared binding is the WebMCP spec URI — the same custom-binding
  // identifier the A2A Agent Card uses — and the endpoint is the page that
  // registers the tools.
  assert.equal(MCP_SERVER_CARD.transport.type, WEBMCP_TRANSPORT_TYPE);
  assert.equal(MCP_SERVER_CARD.transport.type, WEBMCP_PROTOCOL_BINDING);
  assert.equal(MCP_SERVER_CARD.transport.endpoint, 'https://askmilo.pro/');
});

test('capabilities and authentication are declared honestly', () => {
  // Only tools exist on the WebMCP surface — no resources or prompts.
  assert.equal(typeof MCP_SERVER_CARD.capabilities, 'object');
  assert.ok(MCP_SERVER_CARD.capabilities.tools);
  assert.equal(MCP_SERVER_CARD.capabilities.tools.listChanged, false);
  assert.ok(!('resources' in MCP_SERVER_CARD.capabilities));
  assert.ok(!('prompts' in MCP_SERVER_CARD.capabilities));
  // Nothing behind the surface requires a credential.
  assert.equal(MCP_SERVER_CARD.authentication.required, false);
  assert.deepEqual(MCP_SERVER_CARD.authentication.schemes, []);
});

// ---------------------------------------------------------------------------
// Card ↔ WebMCP tool sync — the card may only offer tools the site runs
// ---------------------------------------------------------------------------

test('tools lists every WebMCP tool the page registers, verbatim', () => {
  const tools = buildTools();
  assert.equal(MCP_SERVER_CARD.tools.length, tools.length);
  const byName = new Map(MCP_SERVER_CARD.tools.map((t) => [t.name, t]));
  for (const tool of tools) {
    const listed = byName.get(tool.name);
    assert.ok(listed, `tool ${tool.name} is missing from the card`);
    assert.equal(listed.title, tool.title);
    assert.equal(listed.description, tool.description);
    assert.deepEqual(listed.inputSchema, tool.inputSchema);
  }
});

test('card lists no tool the site does not register', () => {
  const names = new Set(buildTools().map((t) => t.name));
  for (const tool of MCP_SERVER_CARD.tools) {
    assert.ok(names.has(tool.name), `${tool.name} is not a real WebMCP tool`);
  }
});

// ---------------------------------------------------------------------------
// Build wiring — the card must actually land in dist/
// ---------------------------------------------------------------------------

test('well-known.mjs emits the card at the probed path', () => {
  assert.match(wellKnownSrc, /mcp-server-card\.mjs/);
  assert.ok(
    wellKnownSrc.includes(`dist${MCP_SERVER_CARD_PATH}`),
    `well-known.mjs must write dist${MCP_SERVER_CARD_PATH}`,
  );
});

test('card URL and path are the ones the scanner probes', () => {
  assert.equal(MCP_SERVER_CARD_PATH, '/.well-known/mcp/server-card.json');
  assert.equal(
    MCP_SERVER_CARD_URL,
    'https://askmilo.pro/.well-known/mcp/server-card.json',
  );
});

test('serialized card is JSON and free of secret-scan hazard strings', () => {
  const serialized = JSON.stringify(buildServerCard());
  assert.doesNotThrow(() => JSON.parse(serialized));
  // The slugged App Store URL shape matches the sk-* real-key scan; the
  // canonical id-only URL is the only acceptable form.
  assert.doesNotMatch(serialized, /sk-milo/);
});

// ---------------------------------------------------------------------------
// Live-response evaluation — the verdict the verifier reports
// ---------------------------------------------------------------------------

test('evaluate passes a 200 response carrying the canonical card', () => {
  const res = evaluateServerCardResponse({
    ok: true,
    status: 200,
    contentType: 'application/json',
    body: JSON.stringify(MCP_SERVER_CARD),
  });
  assert.equal(res.status, 'pass');
  assert.equal(res.evidence.httpStatus, 200);
});

test('evaluate fails a 404 the way the scanner saw it', () => {
  const res = evaluateServerCardResponse({
    ok: false,
    status: 404,
    contentType: 'text/html; charset=utf-8',
    body: '<html>not found</html>',
  });
  assert.equal(res.status, 'fail');
  assert.match(res.message, /404/);
});

test('evaluate fails on non-JSON and on missing required fields', () => {
  assert.equal(
    evaluateServerCardResponse({
      ok: true,
      status: 200,
      contentType: 'application/json',
      body: 'not json{',
    }).status,
    'fail',
  );
  const res = evaluateServerCardResponse({
    ok: true,
    status: 200,
    contentType: 'application/json',
    body: JSON.stringify({ serverInfo: { name: 'x', version: '1' } }),
  });
  assert.equal(res.status, 'fail');
  assert.match(res.message, /transport|capabilities/);
});

test('validateServerCard flags broken serverInfo, transport and tools', () => {
  const broken = buildServerCard();
  broken.serverInfo = { name: '' };
  const { ok, problems } = validateServerCard(broken);
  assert.equal(ok, false);
  assert.ok(problems.some((p) => p.includes('serverInfo')));

  const noTransport = buildServerCard();
  delete noTransport.transport;
  assert.equal(validateServerCard(noTransport).ok, false);

  const emptyCaps = buildServerCard();
  emptyCaps.capabilities = {};
  const capsResult = validateServerCard(emptyCaps);
  assert.equal(capsResult.ok, false);
  assert.ok(capsResult.problems.some((p) => p.includes('capabilities')));

  const badTools = buildServerCard();
  badTools.tools = [{ title: 'unnamed' }];
  assert.equal(validateServerCard(badTools).ok, false);
});
